### ISSUE TITLE
NPM error in react example.

### ISSUE THREAD

**Issue by rbtcollins** [unleash-hosted/unleash-proxy-client-js#11]
```
npm build
echo PORT=3001 > .env
npm start
curl http://localhost:3001
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:1039:7)
    at noopServiceWorkerMiddleware (/home/robertc/src/unleash-proxy-client-js/examples/react-app/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/home/robertc/src/unleash-proxy-client-js/examples/react-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/robertc/src/unleash-proxy-client-js/examples/react-app/node_modules/express/lib/router/index.js:317:13)
    at /home/robertc/src/unleash-proxy-client-js/examples/react-app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/robertc/src/unleash-proxy-client-js/examples/react-app/node_modules/express/lib/router/index.js:335:12)
    at next (/home/robertc/src/unleash-proxy-client-js/examples/react-app/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/home/robertc/src/unleash-proxy-client-js/examples/react-app/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/home/robertc/src/unleash-proxy-client-js/examples/react-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/robertc/src/unleash-proxy-client-js/examples/react-app/node_modules/express/lib/router/index.js:317:13)
    at /home/robertc/src/unleash-proxy-client-js/examples/react-app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/robertc/src/unleash-proxy-client-js/examples/react-app/node_modules/express/lib/router/index.js:335:12)
    at next (/home/robertc/src/unleash-proxy-client-js/examples/react-app/node_modules/express/lib/router/index.js:275:10)
    at handleWebpackInternalMiddleware (/home/robertc/src/unleash-proxy-client-js/examples/react-app/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (/home/robertc/src/unleash-proxy-client-js/examples/react-app/node_modules/express/lib/router/layer.js:95:5)
```

Not sure why this is happening - perhaps some bitrot with time?

**Comment by ivarconr** [comment]
Thanks, 

For some reason one of the dependencies was sticked to the wrong version. 

Fixed in https://github.com/unleash-hosted/unleash-proxy-client-js/commit/e3098f5dae6f26d6dd234b9b88650e4974d4badc
